apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui-d
spec:
  progressDeadlineSeconds: 20
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui-d
  template:
    metadata:
      labels:
        app: guestbook-ui-d
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:tag
        name: guestbook-ui
        ports:
        - containerPort: 80
