---
name: push

on:
  push:
    branches:
      - main

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      issues: write
      pull-requests: write
      statuses: write
    steps:
      - name: show event
        run: |
          echo ${GITHUB_EVENT_PATH}
          cat ${GITHUB_EVENT_PATH}
      - name: Post text to a Slack channel
        uses: slackapi/slack-github-action@v2.1.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: mikew-argocdnotification
            text: "i6-biosphere PR merged at ${{ github.event.head_commit.timestamp }}"
            attachments:
              - color: "28a745"
                fields:
                  - title: "Author"
                    short: false
                    value: "${{ github.event.head_commit.author.name }}"
                  - title: "Message"
                    short: true
                    value: "<${{ github.event.head_commit.url }}|${{ github.event.head_commit.message }}>"
