---
name: push

on:
  push:
    branches:
      - main

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      issues: write
      pull-requests: write
      statuses: write
    env:
      CHANGED_FILES:
    steps:
      - name: show event
        run: |
          echo ${GITHUB_EVENT_PATH}
          cat ${GITHUB_EVENT_PATH}

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Modified files
        run: |
          case '${{ github.event_name }}' in
            push)
              firstCommit='${{ github.event.before }}'
              lastCommit='${{ github.event.after }}'
              ;;
            pull_request)
              firstCommit='${{ github.event.base_ref }}'
              lastCommit='${{ github.event.head_ref }}'
              ;;
          esac
          echo "CHANGED_FILES<<EOF" >> $GITHUB_ENV
          git diff --name-only --diff-filter=d "${firstCommit}~1" "${lastCommit}" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Post text to a Slack channel
        uses: slackapi/slack-github-action@v2.1.0
        with:
          method: chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            channel: mikew-argocdnotification
            text: "i6-biosphere PR merged at ${{ github.event.head_commit.timestamp }}"
            attachments:
              - color: "28a745"
                fields:
                  - title: "Author"
                    short: true
                    value: "${{ github.event.head_commit.author.name }}"
                  - title: "Revision"
                    short: false
                    value: "<${{ github.event.head_commit.url }}|${{ github.event.head_commit.id }}>"
                  - title: "Message"
                    short: false
                    value: "${{ github.event.head_commit.message }}"
                  - title: "Files"
                    short: false
                    value: "${{ env.CHANGED_FILES }}"
